export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS_SUCCESS';

export const ADD_FAVORITE = 'ADD_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE_SUCCESS';
